language: ruby
rvm:
  - jruby-19mode
  - jruby-20mode
env:
  - "PGVERSION=9.2.4-1-linux-x64 PATH=\"/opt/PostgreSQL/9.2/bin:$PATH\""
before_install:
  - bundle install
  # Download and install postgresql version to test against in /opt
  # (for non-cross compile only)
  - "if [ -z \"$PGCROSS\" ]; then
      wget http://get.enterprisedb.com/postgresql/postgresql-$PGVERSION.run &&
      chmod +x postgresql-$PGVERSION.run &&
      sudo ./postgresql-$PGVERSION.run --mode unattended --unattendedmodeui minimal;
    fi"
script: rake compile test
